// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using contratosimples_api.Application.Core.Data;

#nullable disable

namespace contratosimples_api.Migrations.ContratoSimplesDb
{
    [DbContext(typeof(ContratoSimplesDbContext))]
    [Migration("20250906124708_medicao")]
    partial class medicao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Aditivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Prazo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Aditivo");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.AditivoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AditivoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoAditivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AditivoId");

                    b.HasIndex("ContratoItemId");

                    b.ToTable("AditivoItem");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.CentroDeCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CentroDeCusto");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf_cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.ContatoFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("ContatoFornecedor");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroDeCustoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DtFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DtInicio")
                        .HasColumnType("date");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeCustoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.ContratoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodEscopo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGrupo")
                        .HasColumnType("boolean");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double precision");

                    b.Property<string>("UnMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorUnit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("ContratoItem");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avaliacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf_cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Medicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Medicao");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.MedicaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemContratoId");

                    b.HasIndex("MedicaoId");

                    b.ToTable("MedicaoItem");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Aditivo", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.AditivoItem", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Aditivo", "Aditivo")
                        .WithMany("ItensAditivo")
                        .HasForeignKey("AditivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.ContratoItem", "ContratoItem")
                        .WithMany()
                        .HasForeignKey("ContratoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aditivo");

                    b.Navigation("ContratoItem");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.ContatoFornecedor", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Fornecedor", null)
                        .WithMany("Contatos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Contrato", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.CentroDeCusto", "CentroDeCusto")
                        .WithMany()
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroDeCusto");

                    b.Navigation("Cliente");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.ContratoItem", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Contrato", null)
                        .WithMany("Itens")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.ContratoItem", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Medicao", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.MedicaoItem", b =>
                {
                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.ContratoItem", "ItemContrato")
                        .WithMany()
                        .HasForeignKey("ItemContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contratosimples_api.Application.Core.Models.Entities.Medicao", "Medicao")
                        .WithMany()
                        .HasForeignKey("MedicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemContrato");

                    b.Navigation("Medicao");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Aditivo", b =>
                {
                    b.Navigation("ItensAditivo");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Contrato", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("contratosimples_api.Application.Core.Models.Entities.Fornecedor", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
